[package]
name = "multi-send"
version = "0.1.0"
authors = ["wiasliaw <leewei48750@gmail.com>"]
edition = "2018"

[dependencies]
solana-program = "1.6.10"
thiserror = "1.0.25"

[dev-dependencies]
solana-program-test = "1.6.10"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]
